### ISSUE TITLE
Options have been depreciated.

### ISSUE THREAD

**Issue by jsgao0** [easy-webpack/core#43]
I've got following error message after I executed `npm run build:prod` as of a few days ago. 

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
/home/user/webapp/node_modules/extract-text-webpack-plugin/schema/validator.js:11
		throw new Error(ajv.errorsText());
		^

Error: data['sourceMap'] should NOT have additional properties
    at validate (/home/user/webapp/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
    at new ExtractTextPlugin (/home/user/webapp/node_modules/extract-text-webpack-plugin/index.js:125:3)
    at Object.css (/home/user/webapp/node_modules/@easy-webpack/config-sass/node_modules/@easy-webpack/config-css/src/index.ts:33:25)
    at generateConfig (/home/user/webapp/node_modules/@easy-webpack/core/src/index.ts:71:40)
    at Object.<anonymous> (/home/user/webapp/webpack.config.babel.js:76:14)
    at Module._compile (module.js:570:32)
    at loader (/home/user/webapp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/webapp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/user/webapp/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/user/webapp/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/home/user/webapp/node_modules/webpack/bin/convert-argv.js:107:15)
    at Object.<anonymous> (/home/user/webapp/node_modules/webpack/bin/webpack.js:153:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

package information:
```
  "devDependencies": {
    "@easy-webpack/config-aurelia": "^2.2.2",
    "@easy-webpack/config-babel": "^4.0.0",
    "@easy-webpack/config-common-chunks-simple": "^2.0.3",
    "@easy-webpack/config-copy-files": "^1.1.2",
    "@easy-webpack/config-css": "^4.0.0",
    "@easy-webpack/config-env-development": "^2.1.5",
    "@easy-webpack/config-env-production": "^3.0.0",
    "@easy-webpack/config-external-source-maps": "^3.1.0",
    "@easy-webpack/config-fonts-and-images": "^2.1.0",
    "@easy-webpack/config-generate-index-html": "^2.1.1",
    "@easy-webpack/config-global-bluebird": "^2.1.0",
    "@easy-webpack/config-global-jquery": "^2.1.0",
    "@easy-webpack/config-global-regenerator": "^1.2.2",
    "@easy-webpack/config-html": "^3.1.0",
    "@easy-webpack/config-json": "^3.1.0",
    "@easy-webpack/config-sass": "^2.0.1",
    "@easy-webpack/config-test-coverage-istanbul": "^3.2.0",
    "@easy-webpack/config-uglify": "^2.2.3",
    "@easy-webpack/core": "^2.0.0",
    "aurelia-protractor-plugin": "^1.0.1",
    "aurelia-tools": "^1.0.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-transform-class-properties": "^6.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.0.0",
    "babel-register": "^6.18.0",
    "concurrently": "^3.1.0",
    "cross-env": "^3.1.3",
    "del-cli": "^0.2.0",
    "eslint": "^3.12.0",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.2.0",
    "karma-remap-istanbul": "^0.2.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "protractor": "^4.0.11",
    "wait-on": "^2.0.1",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "2.1.0-beta.12"
  }
```

**Comment by niieani** [comment]
Coming from `config-css`. Fix is on the way. https://github.com/easy-webpack/config-css/pull/34/files

**Comment by jsgao0** [comment]
Subscribed. Thanks!
